### ISSUE TITLE
Password validation: Similarity

### ISSUE THREAD

**Issue by hsmett** [HybirdCorp/creme_crm#123]
There is a django password validator that checks that the chosen password is not too close to the user data (username, first_name, last_name, email).

Currently in Creme, when creating a user, this validator only works for the username.
![image](https://user-images.githubusercontent.com/1230876/99788664-b1b0c800-2b21-11eb-81ac-ac41564a0793.png)

The code is here, we set the username of an empty instance of user:
https://github.com/HybirdCorp/creme_crm/blob/master/creme/creme_config/forms/user.py#L93

**Comment by genglert** [comment]
Should be fixed by: https://github.com/HybirdCorp/creme_crm/commit/feab52d6b4036466630d84d0364e826c6954ea5b

**Comment by hsmett** [comment]
Fixed, thanks !
