### ISSUE TITLE
When sending linked mail (on society or contact page), 'Body' field should be filled from 'Body (HTML)' if empty

### ISSUE THREAD

**Issue by erachen** [HybirdCorp/creme_crm#192]
on: tag 2.2.1

not a bug, just a wish ;)

on page society or contact, when clicking on `send an email`,
on the modal window that appear

There is two field: `Body` (plain text) and `Body (HTML)` (text/html)
It may be desirable that if `Body` if left blank, it is automatically filled with a stripped version of `Body (HTML)`

The reverse may be desirable too:
if `Body (HTML)` is left blank, it may be filled automatically with the text version (maybe surrounded with `<code></code>`).

I think, that if `Body (HTML)` is left blank it is not a good idea to drop the html part, as it may increase spam score on some antispam.

**Comment by genglert** [comment]
Good ideas ! I'll code that between 2 major features (but don't know when).
