### ISSUE TITLE
Date does not validate in "alert" form

### ISSUE THREAD

**Issue by erachen** [HybirdCorp/creme_crm#242]
With CremeCRM tag 2.2.4,

on the organisation page (http://localhost:8000/persons/organisation/4)

clic on the brick "Alert": button "new alert"
fill the form, (title, date, time),
whatever is filled for date (for example: 16-07-2021) the form does not validate with an error "enter a valid date and time)

The same error arise for "todo" when filling a "due date"

**Comment by genglert** [comment]
Why "16-07-2021" would raise an error (it's a valid date) ?
If I fill an invalid date like "35-07-2021" an error is raised.

Can you precise the issue ?

**Comment by erachen** [comment]
Well, when I fill `16-07-2021` it raise an error.

gotcha!

Creme settings got a `DATETIME_INPUT_FORMATS=['%d-%m-%Y', ...]`

My configuration is in french, i.e. my `settings.py` contains:
`LANGUAGE_CODE='fr'` and `USE_L10N=True`

As stated in doc, `DATETIME_INPUT_FORMATS` is ignored in settings in favor of the one defined `django/conf/locale/fr/formats.py`.
This `formats.py` does not include the `%d-%m-%Y` strings

it cannot validate.

The solution seems to configure a `formats.py` file per supported language or to set `USE_L10N=False` which probably raise other issues.

**Comment by genglert** [comment]
Creme uses "voluntarily" the default value `USE_L10N=False`. It's not a good thing, and we should pass to `USE_L10N=True` by default, but:
- it's not totally trivial (eg: many unit tests will have to be improved).
- no user asked us to get different format strings of the same Creme instance, based of the used language (and our default configuration is OK for French).

So it's no the most priority task we have.

But you're right, I'll make a comment in our `settings.py`.
