### ISSUE TITLE
SSO authentication

### ISSUE THREAD

**Issue by bmalynovytch** [HybirdCorp/creme_crm#369]
Single Sign On is a must-have feature.
As it needs to override the default authentication mechanism, should the feature be developed like a new "app" / module or should one modify the core code handling authentication ?

**Comment by mrjmad** [comment]
Hello ! 

For SSO, you have two parts. 

First part -> the real SSO stuff. I think an app will be the good choice. And if you are lucky, maybe an app that manages your SSO already exists. For example we have used : 
- https://pypi.org/project/django-okta-auth/ for Okta authentification
- https://djangocas.dev/docs/latest/index.html for CAS system

Second part -> the configuraion and links with Creme (for automatic user creation or automatic role assignment). Configuration part can be do in your specific settings files (like define a specific AUTHENTICATION_BACKENDS). But somethimes you need to add new login template or new python code. To do this, I think a specific django app will be a better solution. Especially when you want to switch to a new version of Crème (like ththe future 2.4)
